# Generated by Django 3.2 on 2021-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210504_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', through='levelupapi.Attendee', to='levelupapi.Gamer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
