# Generated by Django 3.2 on 2021-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_game_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(),
        ),
    ]
