# Generated by Django 3.2 on 2021-05-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20210505_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='organizer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
