# Generated by Django 3.2 on 2021-05-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_auto_20210506_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='game_category',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='name',
            new_name='maker',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='max_players',
            new_name='number_of_players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_players',
        ),
        migrations.AddField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levelupapi.gamer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
